export const DRIVER_STANDINGS = {
  REQUEST: "REQUEST_DRIVER_STANDINGS",
  RESPONSE: "RESPONSE_DRIVER_STANDINGS"
};

export const YEAR_RESULTS = {
  REQUEST: "REQUEST_YEAR_RESULTS",
  RESPONSE: "RESPONSE_YEAR_RESULTS"
};
